name: Build and deploy gh-pages site

on:
  push:
    branches:
      - znai
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    #if: github.ref == 'refs/heads/znai'

    steps:
      - name: checkout source
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Set up grahpviz
        run: sudo apt-get install graphviz

      - name: Build with xvfb enabled
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: mvn -B package -DskipTests

      - name: re-assemble znai for based cleanup
        run: rm -rf znai-docs/target/znai-docs-*.jar znai-docs/target/maven-archiver

      - name: create base index redirect page
        run: cp znai-docs/index.html target/index.html
             
             
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./znai-docs/target/
#          destination_dir: znai
          publish_branch: gh-pages
          force_orphan: true